framework:
    messenger:
        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    use_notify: true
                    check_delayed_interval: 60000
                retry_strategy:
                    max_retries: 3
                    multiplier: 2
            async_umut:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queue_name: kuyruk_umut_1
            async_umut_2:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queue_name: kuyruk_umut_2
            failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'

        routing:
            Symfony\Component\Mailer\Messenger\SendEmailMessage: async
            Symfony\Component\Notifier\Message\ChatMessage: async
            Symfony\Component\Notifier\Message\SmsMessage: async
            App\Message\MyMessage: async_umut
            App\Message\MyMessage_2: async_umut_2

            # Route your messages to the transports
            # 'App\Message\YourMessage': async
